image: ecr.aws.steedos.cn/dockerhub/steedos/gitpod-workspace-base:2.2.5

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5000
    onOpen: ignore
    visibility: public
  - port: 3000
    onOpen: ignore
    visibility: public
  - port: 3100
    onOpen: open-browser
    visibility: public
  - port: 6379
    onOpen: ignore
  - port: 4222
    onOpen: ignore
  - port: 27017
    onOpen: ignore
  - port: 1880 # node-red-app
    onOpen: ignore
    visibility: public
  - port: 9001 # docker
    onOpen: ignore
    visibility: public
  - port: 80
    onOpen: ignore
    visibility: public
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Steedos Platform
    command: |
      echo "ROOT_URL=$(gp url 5000)" >> steedos-platform/.env.local
      docker-compose -f steedos-platform/docker-compose-ee.yml up
  - name: Steedos Packages
    command: |
      echo "METADATA_SERVER=$(gp url 5000)" >> .env.local
      npm config set registry=https://registry.npmmirror.com
      npm install -g steedos-cli
      yarn
      gp await-port 5000
      yarn dev

vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - redhat.vscode-yaml
    - steedos.steedosdx-vscode
    - steedos.steedosdx-vscode-core
    - ms-ceintl.vscode-language-pack-zh-hans
